# Generated by Django 5.0 on 2024-01-01 22:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=100)),
                ('lastName', models.CharField(max_length=100)),
                ('birth_date', models.DateTimeField()),
                ('contact_info', models.CharField(max_length=100)),
                ('phone', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('adress', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('history', models.TextField()),
                ('allergies', models.TextField()),
                ('current_medications', models.TextField()),
                ('symptoms', models.TextField()),
                ('Patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicalRecords', to='patients.patient')),
            ],
        ),
    ]
